sonar.projectKey=aptlogica_base-sdk_831f5ed1-22c6-4f6b-830a-bf0629564fb1

# Exclude test files and SDK from analysis
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/__tests__/**,**/__test__/**,sdk/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info